version: '3'

services: 
    nodeapp:
        build: .
        env_file: ./.env
        environment: 
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PASS=${DB_PASS}
            - PORT=${PORT}
        ports: 
            - ${PORT}:${PORT}
        depends_on:
            - "mysqldb"
        volumes: 
            - nodeapp:/usr/src/app
    mysqldb:
        image: "mysql"
        env_file: ./.env
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes: 
            - db-config:/etc/mysql
            - db-data:/var/lib/mysql

volumes: 
  nodeapp:
  db-config:
  db-data: